title: "jpl blog"
tagline: "Programmer, mathematician, pianist, fencer, crocheter&hellip; and now blogger?"

email: "jlubi333@gmail.com"

url: "http://blog.jlub.in"

permalink: pretty

base_url: "/"
about_url: "/about/"
portfolio_url: "http://jlub.in"

highlighter: "rouge"
