title: "jpl blog"
tagline: "Programmer, pianist, fencer, high schooler&hellip; and now blogger?"

email: "jlubi333@gmail.com"

url: "http://blog.jlub.in"
base_url: ""

portfolio_url: "http://jlub.in"
about_url: "/about/"
